"""
SET UP DEFAULT VALUES
"""

# When being run in colab please set to False
QUERY_POSTGRES = False

# Define seed
SEED = 42

# GerryChain parameters
# Wanted district size in population
TARGET = 120000
# Variable which we are using to create district over target value
VARIABLE = "pob_t_total"
# Parameter for spanning tree method, set to 2 is fine
NODE_REPEATS = 3
# Epson tolerance for map to initialize
INIT_EPSILON = 1
# Error tolerance for districts
EPSILION = 1
# Percentage difference between populations mac vs low
PARTITION_PERCENTAGE = 2
# Maximum number of possible values
TOTAL_STEPS = 56

# From the TOTAL_STEPS obtain the top maps that minimize the population best
TOP_ITERATION = 10

"""
SET UP PROVINCE LEVEL PARAMS
"""

PROVINCE_PARAMS_MAPPER = [
    {
        "province_id": "02",
        "province_name": "Albacete",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "03",
        "province_name": "Alicante",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 163,
    },
    {
        "province_id": "04",
        "province_name": "Almería",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "01",
        "province_name": "Álava",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "33",
        "province_name": "Asturias",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "05",
        "province_name": "Ávila",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 887,
    },
    {
        "province_id": "06",
        "province_name": "Badajoz",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "07",
        "province_name": "Balears, Illes",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 14,
    },
    {
        "province_id": "08",
        "province_name": "Barcelona",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.3,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 148,
    },
    {
        "province_id": "48",
        "province_name": "Bizkaia",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 760,
    },
    {
        "province_id": "09",
        "province_name": "Burgos",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 360,
    },
    {
        "province_id": "10",
        "province_name": "Cáceres",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 630,
    },
    {
        "province_id": "11",
        "province_name": "Cádiz",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 456,
    },
    {
        "province_id": "39",
        "province_name": "Cantabria",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 505,
    },
    {
        "province_id": "12",
        "province_name": "Castellón",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 785,
    },
    {
        "province_id": "13",
        "province_name": "Ciudad Real",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 813,
    },
    {
        "province_id": "14",
        "province_name": "Córdoba",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 99,
    },
    {
        "province_id": "15",
        "province_name": "Coruña, A",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 941,
    },
    {
        "province_id": "16",
        "province_name": "Cuenca",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 606,
    },
    {
        "province_id": "20",
        "province_name": "Gipuzkoa",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 788,
    },
    {
        "province_id": "17",
        "province_name": "Girona",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 520,
    },
    {
        "province_id": "18",
        "province_name": "Granada",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 579,
    },
    {
        "province_id": "19",
        "province_name": "Guadalajara",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 24,
    },
    {
        "province_id": "21",
        "province_name": "Huelva",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "22",
        "province_name": "Huesca",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 543,
    },
    {
        "province_id": "23",
        "province_name": "Jaén",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 610,
    },
    {
        "province_id": "24",
        "province_name": "León",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "25",
        "province_name": "Lleida",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "27",
        "province_name": "Lugo",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 834,
    },
    {
        "province_id": "28",
        "province_name": "Madrid",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "29",
        "province_name": "Málaga",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.3,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "30",
        "province_name": "Murcia",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "31",
        "province_name": "Navarra",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 977,
    },
    {
        "province_id": "32",
        "province_name": "Ourense",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 110,
    },
    {
        "province_id": "34",
        "province_name": "Palencia",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 141,
    },
    {
        "province_id": "35",
        "province_name": "Palmas, Las",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 506,
    },
    {
        "province_id": "36",
        "province_name": "Pontevedra",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 636,
    },
    {
        "province_id": "26",
        "province_name": "Rioja, La",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "37",
        "province_name": "Salamanca",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "38",
        "province_name": "Santa Cruz de Tenerife",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 112,
    },
    {
        "province_id": "40",
        "province_name": "Segovia",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 406,
    },
    {
        "province_id": "41",
        "province_name": "Sevilla",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "42",
        "province_name": "Soria",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.36,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 893,
    },
    {
        "province_id": "43",
        "province_name": "Tarragona",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 42,
    },
    {
        "province_id": "44",
        "province_name": "Teruel",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 45,
    },
    {
        "province_id": "45",
        "province_name": "Toledo",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.25,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 201,
    },
    {
        "province_id": "46",
        "province_name": "Valencia",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 436,
    },
    {
        "province_id": "47",
        "province_name": "Valladolid",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 153,
    },
    {
        "province_id": "49",
        "province_name": "Zamora",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 612,
    },
    {
        "province_id": "50",
        "province_name": "Zaragoza",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.2,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 975,
    },
    {
        "province_id": "51",
        "province_name": "Ceuta",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.42,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 707,
    },
    {
        "province_id": "52",
        "province_name": "Melilla",
        "target": 120000,
        "variable": "pob_t_total",
        "node_repeats": 3,
        "init_epsilon": 0.39,
        "epsilon": 0.1,
        "partition_percentage": 2,
        "total_steps": 56,
        "top_iteration": 10,
        "query_postgres": False,
        "seed": 568,
    }
]

